In [ ]:
!pip install faker pandas

Collecting faker
  Downloading faker-40.13.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading faker-40.13.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 33.4 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.13.0

In [ ]:
from faker import Faker
import pandas as pd
import random
import datetime
fake = Faker()

In [ ]:


# Step 2: Initialize Faker
fake = Faker()

# Step 3: Generate Users Data
users = []

for i in range(100000):  # 50k users
    # Subscription dates
    start_date = fake.date_between(start_date='-5y', end_date='today')
    end_date = start_date + datetime.timedelta(days=random.randint(30, 365))

    # Email: sometimes missing
    email = fake.unique.email()  # guarantees no duplicates
    # Name: messy capitalization
    name = fake.name()
    if random.random() > 0.5:
        name = name.upper()

    # Age: 18–75
    age = random.randint(18, 75)

    # Gender
    gender = random.choice(['Male', 'Female', 'other'])

    # Country
    country = fake.country()

    # Subscription type
    subscription_type = random.choice(['Basic', 'Standard', 'Premium'])

    # Format dates for MySQL
    start_date = start_date.strftime('%Y-%m-%d')
    end_date = end_date.strftime('%Y-%m-%d')

    users.append([
        name,
        email,
        age,
        gender,
        country,
        subscription_type,
        start_date,
        end_date
    ])

# Step 4: Create DataFrame
users_df = pd.DataFrame(users, columns=[
    'name',
    'email',
    'age',
    'gender',
    'country',
    'subscription_type',
    'subscription_start',
    'subscription_end'
])

# Step 5: Save CSV for MySQL
# NULL emails will be saved as NULL (MySQL-compatible)
users_df.to_csv("users.csv", index=False, na_rep='NULL')

# Step 6: Check first 5 rows
users_df.head(10)

,name,email,age,gender,country,subscription_type,subscription_start,subscription_end
0,LORI PITTS,jeffreysandoval@example.net,28,Female,Netherlands Antilles,Premium,2022-11-30,2023-11-18
1,RACHEL CAMPBELL,kimberlymoore@example.com,54,Male,Poland,Basic,2025-03-08,2025-10-05
2,MICHAEL BARNETT,tprice@example.org,48,Male,Mauritania,Standard,2024-12-17,2025-03-16
3,Mary Green,mthompson@example.org,32,Male,Bangladesh,Standard,2025-04-08,2025-09-27
4,Kathleen Miller,latoya85@example.com,26,Male,New Caledonia,Basic,2022-06-03,2022-08-10
5,Jordan Parsons,alexanderturner@example.org,45,other,Portugal,Basic,2021-11-06,2022-02-26
6,Stephen King,zlee@example.com,63,Female,Montserrat,Standard,2022-06-25,2023-01-26
7,Jessica Allen,vanessahancock@example.net,65,Male,Libyan Arab Jamahiriya,Basic,2022-02-07,2023-01-28
8,KATHERINE ANDERSON,asolis@example.com,31,Male,Kiribati,Standard,2023-07-26,2023-11-20
9,Eric Rodriguez,kimberly98@example.net,32,Female,Burundi,Standard,2022-03-21,2022-11-16

In [ ]:
# Step: Generate View table data
fake = Faker()

genres = ['Action', 'Horror', 'Comedy', 'Drama', 'Sci-Fi', 'Documentary', 'Romance', 'Thriller']

content = []

for i in range(50000):
    title = fake.sentence(nb_words=3).replace('.', '')

    # realistic duration
    duration = round(random.uniform(20, 180), 2)

    # realistic rating (more centered around 3–4)
    rating = round(random.uniform(2.0, 4.8), 1)

    content.append([
        title,
        random.choice(genres),
        duration,
        random.randint(1980, 2025),
        rating
    ])

content_df = pd.DataFrame(content, columns=[
    'title',
    'genre',
    'duration_min',
    'release_year',
    'rating'
])

content_df.head()

,title,genre,duration_min,release_year,rating
0,Significant meeting sense whom,Sci-Fi,162.52,1989,2.9
1,Physical role,Sci-Fi,179.46,1993,3.5
2,Recognize low price,Sci-Fi,87.11,2019,3.9
3,People result establish,Action,138.25,2012,2.9
4,Each,Thriller,99.75,1995,3.8

In [ ]:
# Step: Generate View table data

from faker import Faker
import pandas as pd
import random
import datetime

fake = Faker()

# ---- 1. Define valid IDs ----
# User IDs that actually exist in MySQL users table
valid_user_ids = list(range(172, 100172))  # MIN=172, MAX=100171

# Content IDs that actually exist in MySQL content table
valid_content_ids = list(range(1, 50001))  # assuming 50,000 content rows

# Device types
device_types = ['Mobile', 'Desktop', 'Smart_TV', 'Tablet']

# ---- 2. Generate messy View data ----
view_data = []
num_rows = 300000  # number of view records

for _ in range(num_rows):
    user_id = random.choice(valid_user_ids)           # only valid User_id
    content_id = random.choice(valid_content_ids)    # only valid Content_id
    watch_date = fake.date_time_between(start_date='-5y', end_date='now')
    watch_date_str = watch_date.strftime('%Y-%m-%d %H:%M:%S')  # MySQL datetime format
    watch_time = round(random.uniform(5, 180), 2)   # minutes watched
    device = random.choice(device_types)

    # Append as a row
    view_data.append([user_id, content_id, watch_date_str, watch_time, device])

# ---- 3. Create DataFrame ----
view_df = pd.DataFrame(view_data, columns=[
    'User_id', 'content_id', 'watch_date', 'watch_time_minutes', 'device_type'
])

# ---- 4. Preview ----
print(view_df.head())

# ---- 5. Export to CSV for MySQL LOAD DATA ----
view_df.to_csv("view.csv", index=False, na_rep='NULL')
print("CSV file saved as 'view.csv' ready for MySQL import!")

   User_id  content_id           watch_date  watch_time_minutes device_type
0    18717          44  2023-02-11 22:24:42               22.63    Smart_TV
1    19693       17664  2021-12-22 00:19:53              102.44     Desktop
2     7071        9197  2023-08-23 18:58:30              141.37     Desktop
3    43487       18988  2025-02-22 04:38:32              140.06     Desktop
4    70694        4394  2022-02-21 05:58:48              179.36    Smart_TV
CSV file saved as 'view.csv' ready for MySQL import!

In [ ]:
from google.colab import files

In [ ]:
users_df.to_csv('users.csv', index=False)
content_df.to_csv('content.csv', index=False)
view_df.to_csv('view.csv', index=False)
files.download('users.csv')
files.download('content.csv')
files.download('view.csv')

In [ ]:
# import libraries
import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns

In [ ]:
# display all columns in pandas
pd.set_option('display.max_columns',None)

In [ ]:
print('users tables:')
print(users_df.info())
print(users_df.describe)
print(users_df.head())
print(users_df.isnull())

users tables:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   name                100000 non-null  object
 1   email               100000 non-null  object
 2   age                 100000 non-null  int64
 3   gender              100000 non-null  object
 4   country             100000 non-null  object
 5   subscription_type   100000 non-null  object
 6   subscription_start  100000 non-null  object
 7   subscription_end    100000 non-null  object
dtypes: int64(1), object(7)
memory usage: 6.1+ MB
None
<bound method NDFrame.describe of                   name                         email  age  gender  \
0           LORI PITTS   jeffreysandoval@example.net   28  Female
1      RACHEL CAMPBELL     kimberlymoore@example.com   54    Male
2      MICHAEL BARNETT            tprice@example.org   48    Male
3           Mary Green         mthompson@example.org   32    Male
4      Kathleen Miller          latoya85@example.com   26    Male
...                ...                           ...  ...     ...
99995   SARAH MCDANIEL       diazcynthia@example.com   46   other
99996  ANGEL GILLESPIE            ucross@example.net   21   other
99997   MASON HAMILTON       debramiller@example.com   41  Female
99998    Jack Mckinney  perezchristopher@example.net   34    Male
99999      Nicole Dunn         rickyruiz@example.org   59    Male

                    country subscription_type subscription_start  \
0      Netherlands Antilles           Premium         2022-11-30
1                    Poland             Basic         2025-03-08
2                Mauritania          Standard         2024-12-17
3                Bangladesh          Standard         2025-04-08
4             New Caledonia             Basic         2022-06-03
...                     ...               ...                ...
99995              Cambodia           Premium         2022-07-31
99996            Mauritania           Premium         2026-03-11
99997          Turkmenistan             Basic         2025-10-10
99998         Faroe Islands          Standard         2024-03-22
99999                Rwanda           Premium         2025-04-02

      subscription_end
0           2023-11-18
1           2025-10-05
2           2025-03-16
3           2025-09-27
4           2022-08-10
...                ...
99995       2022-09-25
99996       2027-01-12
99997       2025-11-18
99998       2024-07-30
99999       2025-07-25

[100000 rows x 8 columns]>
              name                        email  age  gender  \
0       LORI PITTS  jeffreysandoval@example.net   28  Female
1  RACHEL CAMPBELL    kimberlymoore@example.com   54    Male
2  MICHAEL BARNETT           tprice@example.org   48    Male
3       Mary Green        mthompson@example.org   32    Male
4  Kathleen Miller         latoya85@example.com   26    Male

                country subscription_type subscription_start subscription_end
0  Netherlands Antilles           Premium         2022-11-30       2023-11-18
1                Poland             Basic         2025-03-08       2025-10-05
2            Mauritania          Standard         2024-12-17       2025-03-16
3            Bangladesh          Standard         2025-04-08       2025-09-27
4         New Caledonia             Basic         2022-06-03       2022-08-10
        name  email    age  gender  country  subscription_type  \
0      False  False  False   False    False              False
1      False  False  False   False    False              False
2      False  False  False   False    False              False
3      False  False  False   False    False              False
4      False  False  False   False    False              False
...      ...    ...    ...     ...      ...                ...
99995  False  False  False   False    False              False
99996  False  False  False   False    False              False
99997  False  False  False   False    False              False
99998  False  False  False   False    False              False
99999  False  False  False   False    False              False

       subscription_start  subscription_end
0                   False             False
1                   False             False
2                   False             False
3                   False             False
4                   False             False
...                   ...               ...
99995               False             False
99996               False             False
99997               False             False
99998               False             False
99999               False             False

[100000 rows x 8 columns]

In [ ]:
# checking missinf users value
print(users_df.isnull().sum())

name                  0
email                 0
age                   0
gender                0
country               0
subscription_type     0
subscription_start    0
subscription_end      0
dtype: int64

In [ ]:
# checking types
print(users_df.dtypes)

name                  object
email                 object
age                    int64
gender                object
country               object
subscription_type     object
subscription_start    object
subscription_end      object
dtype: object

In [ ]:
# subscription_start and subscription_end still in object so changing in into datetime
users_df['subscription_start'] = pd.to_datetime(users_df['subscription_start'])
users_df['subscription_end'] = pd.to_datetime(users_df['subscription_end'])
# now we wil see datetime
print(users_df.dtypes)

name                          object
email                         object
age                            int64
gender                        object
country                       object
subscription_type             object
subscription_start    datetime64[ns]
subscription_end      datetime64[ns]
dtype: object

In [ ]:
# now making gender and subscription_type into categorical

users_df['gender'] = users_df['gender'].astype('category')
users_df['subscription_type'] = users_df['subscription_type'].astype('category')
# now checking dtypes
print(users_df.dtypes)

name                          object
email                         object
age                            int64
gender                      category
country                       object
subscription_type           category
subscription_start    datetime64[ns]
subscription_end      datetime64[ns]
dtype: object

In [ ]:
# creating a new feature called subscription_duration
users_df['subscription_duration'] = (
    users_df['subscription_end'] - users_df['subscription_start']
    ).dt.days
print(users_df['subscription_duration'])

0        353
1        211
2         89
3        172
4         68
        ...
99995     56
99996    307
99997     39
99998    130
99999    114
Name: subscription_duration, Length: 100000, dtype: int64

In [ ]:
# creating another new gfeature age_group
users_df['age_group'] = pd.cut (
    users_df['age'],
    bins = [18,25,35,50,65,75],
    labels=['18-25','26-35','36-50','51-65','66-75']
)
print(users_df['age_group'])

0        26-35
1        51-65
2        36-50
3        26-35
4        26-35
         ...
99995    36-50
99996    18-25
99997    36-50
99998    26-35
99999    51-65
Name: age_group, Length: 100000, dtype: category
Categories (5, object): ['18-25' < '26-35' < '36-50' < '51-65' < '66-75']

In [ ]:
# extracting year and month
users_df['start_year'] = users_df['subscription_start'].dt.year
users_df['start_month'] = users_df['subscription_start'].dt.month
print(users_df['start_year'])
print(users_df['start_month'])

0        2022
1        2025
2        2024
3        2025
4        2022
         ...
99995    2022
99996    2026
99997    2025
99998    2024
99999    2025
Name: start_year, Length: 100000, dtype: int32
0        11
1         3
2        12
3         4
4         6
         ..
99995     7
99996     3
99997    10
99998     3
99999     4
Name: start_month, Length: 100000, dtype: int32

In [ ]:
users_df.head(5)

,name,email,age,gender,country,subscription_type,subscription_start,subscription_end,subscription_duration,age_group,start_year,start_month
0,LORI PITTS,jeffreysandoval@example.net,28,Female,Netherlands Antilles,Premium,2022-11-30,2023-11-18,353,26-35,2022,11
1,RACHEL CAMPBELL,kimberlymoore@example.com,54,Male,Poland,Basic,2025-03-08,2025-10-05,211,51-65,2025,3
2,MICHAEL BARNETT,tprice@example.org,48,Male,Mauritania,Standard,2024-12-17,2025-03-16,89,36-50,2024,12
3,Mary Green,mthompson@example.org,32,Male,Bangladesh,Standard,2025-04-08,2025-09-27,172,26-35,2025,4
4,Kathleen Miller,latoya85@example.com,26,Male,New Caledonia,Basic,2022-06-03,2022-08-10,68,26-35,2022,6

In [ ]:
# users per subscription type
users_df.groupby('subscription_type').size()

/tmp/ipykernel_1307/642442302.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  users_df.groupby('subscription_type').size()

subscription_type
Basic       33536
Premium     33258
Standard    33206
dtype: int64

In [ ]:
# most pouplar
users_df.groupby('subscription_type').size().sort_values(ascending = False)

/tmp/ipykernel_1307/1736296505.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  users_df.groupby('subscription_type').size().sort_values(ascending = False)

subscription_type
Basic       33536
Premium     33258
Standard    33206
dtype: int64

In [ ]:
# average subscription day
users_df.groupby('subscription_type')['subscription_duration'].mean().sort_values(ascending = False)

/tmp/ipykernel_1307/3999752269.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  users_df.groupby('subscription_type')['subscription_duration'].mean().sort_values(ascending = False)

subscription_type
Premium     198.039389
Basic       197.729276
Standard    197.398723
Name: subscription_duration, dtype: float64

In [ ]:
# combine count and Average

users_df.groupby('subscription_type').agg(
     user_count =('name' , 'count'),
    avg_subscription_duration =( 'subscription_duration' , 'mean')
)

/tmp/ipykernel_1307/2442647106.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  users_df.groupby('subscription_type').agg(

                   user_count  avg_subscription_duration
subscription_type
Basic                   33536                 197.729276
Premium                 33258                 198.039389
Standard                33206                 197.398723

In [ ]:
# content table
content_df.head()

,title,genre,duration_min,release_year,rating
0,Significant meeting sense whom,Sci-Fi,162.52,1989,2.9
1,Physical role,Sci-Fi,179.46,1993,3.5
2,Recognize low price,Sci-Fi,87.11,2019,3.9
3,People result establish,Action,138.25,2012,2.9
4,Each,Thriller,99.75,1995,3.8

In [ ]:
content_df. describe()
content_df. info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         50000 non-null  object
 1   genre         50000 non-null  object
 2   duration_min  50000 non-null  float64
 3   release_year  50000 non-null  int64
 4   rating        50000 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 1.9+ MB

In [ ]:
# converting genre intp category
content_df['genre'].astype('category')

0             Sci-Fi
1             Sci-Fi
2             Sci-Fi
3             Action
4           Thriller
            ...
49995    Documentary
49996         Horror
49997    Documentary
49998       Thriller
49999    Documentary
Name: genre, Length: 50000, dtype: category
Categories (8, object): ['Action', 'Comedy', 'Documentary', 'Drama', 'Horror', 'Romance', 'Sci-Fi',
                         'Thriller']

In [ ]:
# counting
content_df.value_counts('genre')

genre
Action         6432
Drama          6342
Thriller       6315
Sci-Fi         6268
Horror         6205
Romance        6201
Comedy         6162
Documentary    6075
Name: count, dtype: int64

In [ ]:
# avg rating by genre

content_df.groupby('genre')['rating'].mean().sort_values(ascending = False)

genre
Action         3.414412
Romance        3.402161
Drama          3.396263
Sci-Fi         3.391991
Horror         3.389234
Thriller       3.388203
Documentary    3.387918
Comedy         3.376371
Name: rating, dtype: float64

In [ ]:
# avg duration by genre

content_df.groupby('genre')['duration_min'].mean().sort_values(ascending = False)

genre
Sci-Fi         100.847806
Comedy          99.992064
Thriller        99.954928
Documentary     99.648430
Horror          99.618326
Action          99.587313
Romance         99.293193
Drama           99.267390
Name: duration_min, dtype: float64

In [ ]:
# view table
view_df.head()

   User_id  content_id           watch_date  watch_time_minutes device_type
0    18717          44  2023-02-11 22:24:42               22.63    Smart_TV
1    19693       17664  2021-12-22 00:19:53              102.44     Desktop
2     7071        9197  2023-08-23 18:58:30              141.37     Desktop
3    43487       18988  2025-02-22 04:38:32              140.06     Desktop
4    70694        4394  2022-02-21 05:58:48              179.36    Smart_TV

In [ ]:
view_df.describe()
view_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 5 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   User_id             300000 non-null  int64
 1   content_id          300000 non-null  int64
 2   watch_date          300000 non-null  object
 3   watch_time_minutes  300000 non-null  float64
 4   device_type         300000 non-null  object
dtypes: float64(1), int64(2), object(2)
memory usage: 11.4+ MB

In [ ]:
view_df['watch_date'] = pd.to_datetime(view_df['watch_date'],errors='coerce')
print(view_df)

        User_id  content_id          watch_date  watch_time_minutes  \
0         18717          44 2023-02-11 22:24:42               22.63
1         19693       17664 2021-12-22 00:19:53              102.44
2          7071        9197 2023-08-23 18:58:30              141.37
3         43487       18988 2025-02-22 04:38:32              140.06
4         70694        4394 2022-02-21 05:58:48              179.36
...         ...         ...                 ...                 ...
299995    62620       21048 2021-04-30 06:39:22               72.79
299996    58045        4930 2024-02-14 10:31:25               10.23
299997    92884       11086 2022-07-20 18:49:34              112.94
299998     6089       38437 2025-12-23 06:51:40              173.18
299999    67059       26044 2026-02-03 01:17:51              126.36

       device_type
0         Smart_TV
1          Desktop
2          Desktop
3          Desktop
4         Smart_TV
...            ...
299995     Desktop
299996     Desktop
299997      Mobile
299998     Desktop
299999      Mobile

[300000 rows x 5 columns]

In [ ]:
# add useful columns
view_df['watch_year'] = view_df['watch_date'].dt.year
view_df['watch_month'] = view_df['watch_date'].dt.month
view_df['watch_dayofweek'] = view_df['watch_date'].dt.day_name()
view_df

,User_id,content_id,watch_date,watch_time_minutes,device_type,watch_year,watch_month,watch_dayofweek
0,18717,44,2023-02-11 22:24:42,22.63,Smart_TV,2023,2,Saturday
1,19693,17664,2021-12-22 00:19:53,102.44,Desktop,2021,12,Wednesday
2,7071,9197,2023-08-23 18:58:30,141.37,Desktop,2023,8,Wednesday
3,43487,18988,2025-02-22 04:38:32,140.06,Desktop,2025,2,Saturday
4,70694,4394,2022-02-21 05:58:48,179.36,Smart_TV,2022,2,Monday
...,...,...,...,...,...,...,...,...
299995,62620,21048,2021-04-30 06:39:22,72.79,Desktop,2021,4,Friday
299996,58045,4930,2024-02-14 10:31:25,10.23,Desktop,2024,2,Wednesday
299997,92884,11086,2022-07-20 18:49:34,112.94,Mobile,2022,7,Wednesday
299998,6089,38437,2025-12-23 06:51:40,173.18,Desktop,2025,12,Tuesday
299999,67059,26044,2026-02-03 01:17:51,126.36,Mobile,2026,2,Tuesday

In [ ]:
# checking
view_df['device_type'].value_counts()

device_type
Desktop     75140
Tablet      74984
Mobile      74981
Smart_TV    74895
Name: count, dtype: int64

In [ ]:
# checking

view_df['watch_year'].value_counts().sort_values(ascending = False)

watch_year
2023    60198
2024    60183
2025    60022
2022    59725
2021    44163
2026    15709
Name: count, dtype: int64

In [ ]:
print(users_df.columns)
print(view_df.columns)

Index(['name', 'email', 'age', 'gender', 'country', 'subscription_type',
       'subscription_start', 'subscription_end', 'subscription_duration',
       'age_group', 'start_year', 'start_month'],
      dtype='object')
Index(['User_id', 'content_id', 'watch_date', 'watch_time_minutes',
       'device_type', 'watch_year', 'watch_month', 'watch_dayofweek'],
      dtype='object')

In [ ]:
# Step : Add User_id to users_df
users_df['User_id'] = range(1, len(users_df)+1)

# Step : Merge users and view
user_view_df = view_df.merge(users_df, on='User_id', how='left')

# Step : Merge the above with content_df
full_df = user_view_df.merge(content_df, on='content_id', how='left')

# Step : Quick check
full_df.head()

,User_id,content_id,watch_date,watch_time_minutes,device_type,watch_year,watch_month,watch_dayofweek,name,email,age,gender,country,subscription_type,subscription_start,subscription_end,subscription_duration,age_group,start_year,start_month,title,genre,duration_min,release_year,rating
0,18717,44,2023-02-11 22:24:42,22.63,Smart_TV,2023,2,Saturday,MR. BRIAN LEBLANC,mark21@example.org,48.0,Male,Grenada,Standard,2024-11-12,2025-11-04,357.0,36-50,2024.0,11.0,Or show,Sci-Fi,139.96,2013,3.9
1,19693,17664,2021-12-22 00:19:53,102.44,Desktop,2021,12,Wednesday,Michael Garza,christinelopez@example.net,32.0,Female,Lebanon,Basic,2024-07-10,2025-06-20,345.0,26-35,2024.0,7.0,Responsibility can lawyer,Comedy,93.60,2006,2.6
2,7071,9197,2023-08-23 18:58:30,141.37,Desktop,2023,8,Wednesday,Daniel Franklin,morgandonovan@example.com,62.0,other,Djibouti,Basic,2023-03-21,2023-04-24,34.0,51-65,2023.0,3.0,Step that,Comedy,30.92,2025,4.5
3,43487,18988,2025-02-22 04:38:32,140.06,Desktop,2025,2,Saturday,MONIQUE BLACK,kellimiller@example.org,33.0,Female,Togo,Basic,2021-11-10,2022-07-04,236.0,26-35,2021.0,11.0,Her media,Sci-Fi,172.23,2008,4.6
4,70694,4394,2022-02-21 05:58:48,179.36,Smart_TV,2022,2,Monday,TODD NELSON,phillipsmiranda@example.com,37.0,Female,Dominica,Standard,2022-03-30,2023-01-13,289.0,36-50,2022.0,3.0,Believe tend hand,Documentary,177.81,1986,3.0

In [ ]:
# Step : Add content_id to content_df
content_df['content_id'] = range(1, len(content_df)+1)

# Step : Merge users and view (ensure users_df has User_id)
users_df['User_id'] = range(1, len(users_df)+1)
user_view_df = view_df.merge(users_df, on='User_id', how='left')

# Step : Merge the above with content_df
full_df = user_view_df.merge(content_df, on='content_id', how='left')

# Step : Check the merged dataframe
full_df.head()

,User_id,content_id,watch_date,watch_time_minutes,device_type,watch_year,watch_month,watch_dayofweek,name,email,age,gender,country,subscription_type,subscription_start,subscription_end,subscription_duration,age_group,start_year,start_month,title,genre,duration_min,release_year,rating
0,18717,44,2023-02-11 22:24:42,22.63,Smart_TV,2023,2,Saturday,MR. BRIAN LEBLANC,mark21@example.org,48.0,Male,Grenada,Standard,2024-11-12,2025-11-04,357.0,36-50,2024.0,11.0,Or show,Sci-Fi,139.96,2013,3.9
1,19693,17664,2021-12-22 00:19:53,102.44,Desktop,2021,12,Wednesday,Michael Garza,christinelopez@example.net,32.0,Female,Lebanon,Basic,2024-07-10,2025-06-20,345.0,26-35,2024.0,7.0,Responsibility can lawyer,Comedy,93.60,2006,2.6
2,7071,9197,2023-08-23 18:58:30,141.37,Desktop,2023,8,Wednesday,Daniel Franklin,morgandonovan@example.com,62.0,other,Djibouti,Basic,2023-03-21,2023-04-24,34.0,51-65,2023.0,3.0,Step that,Comedy,30.92,2025,4.5
3,43487,18988,2025-02-22 04:38:32,140.06,Desktop,2025,2,Saturday,MONIQUE BLACK,kellimiller@example.org,33.0,Female,Togo,Basic,2021-11-10,2022-07-04,236.0,26-35,2021.0,11.0,Her media,Sci-Fi,172.23,2008,4.6
4,70694,4394,2022-02-21 05:58:48,179.36,Smart_TV,2022,2,Monday,TODD NELSON,phillipsmiranda@example.com,37.0,Female,Dominica,Standard,2022-03-30,2023-01-13,289.0,36-50,2022.0,3.0,Believe tend hand,Documentary,177.81,1986,3.0

In [ ]:
# checking missing values
full_df.isnull().sum()

User_id                     0
content_id                  0
watch_date                  0
watch_time_minutes          0
device_type                 0
watch_year                  0
watch_month                 0
watch_dayofweek             0
name                      488
email                     488
age                       488
gender                    488
country                   488
subscription_type         488
subscription_start        488
subscription_end          488
subscription_duration     488
age_group                5722
start_year                488
start_month               488
title                       0
genre                       0
duration_min                0
release_year                0
rating                      0
dtype: int64

In [ ]:
# changes into category
full_df['genre'].astype('category')
full_df['gender'].astype('category')
full_df['country'].astype('category')
full_df['subscription_type'].astype('category')
full_df['device_type'].astype('category')

0         Smart_TV
1          Desktop
2          Desktop
3          Desktop
4         Smart_TV
            ...
299995     Desktop
299996     Desktop
299997      Mobile
299998     Desktop
299999      Mobile
Name: device_type, Length: 300000, dtype: category
Categories (4, object): ['Desktop', 'Mobile', 'Smart_TV', 'Tablet']

In [ ]:
full_df['subscription_start'] = pd.to_datetime(full_df['subscription_start'])
full_df['subscription_end'] = pd.to_datetime(full_df['subscription_end'])
full_df['watch_date'] = pd.to_datetime(full_df['watch_date'])
full_df

,User_id,content_id,watch_date,watch_time_minutes,device_type,watch_year,watch_month,watch_dayofweek,name,email,age,gender,country,subscription_type,subscription_start,subscription_end,subscription_duration,age_group,start_year,start_month,title,genre,duration_min,release_year,rating
0,18717,44,2023-02-11 22:24:42,22.63,Smart_TV,2023,2,Saturday,MR. BRIAN LEBLANC,mark21@example.org,48.0,Male,Grenada,Standard,2024-11-12,2025-11-04,357.0,36-50,2024.0,11.0,Or show,Sci-Fi,139.96,2013,3.9
1,19693,17664,2021-12-22 00:19:53,102.44,Desktop,2021,12,Wednesday,Michael Garza,christinelopez@example.net,32.0,Female,Lebanon,Basic,2024-07-10,2025-06-20,345.0,26-35,2024.0,7.0,Responsibility can lawyer,Comedy,93.60,2006,2.6
2,7071,9197,2023-08-23 18:58:30,141.37,Desktop,2023,8,Wednesday,Daniel Franklin,morgandonovan@example.com,62.0,other,Djibouti,Basic,2023-03-21,2023-04-24,34.0,51-65,2023.0,3.0,Step that,Comedy,30.92,2025,4.5
3,43487,18988,2025-02-22 04:38:32,140.06,Desktop,2025,2,Saturday,MONIQUE BLACK,kellimiller@example.org,33.0,Female,Togo,Basic,2021-11-10,2022-07-04,236.0,26-35,2021.0,11.0,Her media,Sci-Fi,172.23,2008,4.6
4,70694,4394,2022-02-21 05:58:48,179.36,Smart_TV,2022,2,Monday,TODD NELSON,phillipsmiranda@example.com,37.0,Female,Dominica,Standard,2022-03-30,2023-01-13,289.0,36-50,2022.0,3.0,Believe tend hand,Documentary,177.81,1986,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,62620,21048,2021-04-30 06:39:22,72.79,Desktop,2021,4,Friday,Nicholas Walls,tracygoodwin@example.com,59.0,other,Saint Pierre and Miquelon,Basic,2021-04-11,2021-09-09,151.0,51-65,2021.0,4.0,Candidate career,Horror,72.52,1998,4.0
299996,58045,4930,2024-02-14 10:31:25,10.23,Desktop,2024,2,Wednesday,Mr. Jordan Taylor,devonrodgers@example.org,70.0,Female,Jordan,Standard,2024-12-26,2025-03-30,94.0,66-75,2024.0,12.0,Bank such,Sci-Fi,165.66,2002,3.4
299997,92884,11086,2022-07-20 18:49:34,112.94,Mobile,2022,7,Wednesday,Christina Castillo,marquezmatthew@example.org,38.0,Female,Kiribati,Standard,2023-11-10,2023-12-20,40.0,36-50,2023.0,11.0,Dog investment,Comedy,113.45,2014,3.2
299998,6089,38437,2025-12-23 06:51:40,173.18,Desktop,2025,12,Tuesday,Ernest Davis,richard83@example.com,30.0,other,Namibia,Basic,2022-09-16,2023-06-08,265.0,26-35,2022.0,9.0,Shoulder technology newspaper,Action,133.52,2005,4.6
299999,67059,26044,2026-02-03 01:17:51,126.36,Mobile,2026,2,Tuesday,Kathryn Diaz,sandrajohnson@example.net,72.0,Male,Heard Island and McDonald Islands,Standard,2022-03-29,2022-10-29,214.0,66-75,2022.0,3.0,Team long,Documentary,144.82,2000,3.3

In [ ]:
# Feature Engineering : Subscription duration in  days
full_df['subscription_days'] = (full_df['subscription_end'] - full_df['subscription_start']).dt.days
full_df

,User_id,content_id,watch_date,watch_time_minutes,device_type,watch_year,watch_month,watch_dayofweek,name,email,age,gender,country,subscription_type,subscription_start,subscription_end,subscription_duration,age_group,start_year,start_month,title,genre,duration_min,release_year,rating,subscription_days
0,18717,44,2023-02-11 22:24:42,22.63,Smart_TV,2023,2,Saturday,MR. BRIAN LEBLANC,mark21@example.org,48.0,Male,Grenada,Standard,2024-11-12,2025-11-04,357.0,36-50,2024.0,11.0,Or show,Sci-Fi,139.96,2013,3.9,357.0
1,19693,17664,2021-12-22 00:19:53,102.44,Desktop,2021,12,Wednesday,Michael Garza,christinelopez@example.net,32.0,Female,Lebanon,Basic,2024-07-10,2025-06-20,345.0,26-35,2024.0,7.0,Responsibility can lawyer,Comedy,93.60,2006,2.6,345.0
2,7071,9197,2023-08-23 18:58:30,141.37,Desktop,2023,8,Wednesday,Daniel Franklin,morgandonovan@example.com,62.0,other,Djibouti,Basic,2023-03-21,2023-04-24,34.0,51-65,2023.0,3.0,Step that,Comedy,30.92,2025,4.5,34.0
3,43487,18988,2025-02-22 04:38:32,140.06,Desktop,2025,2,Saturday,MONIQUE BLACK,kellimiller@example.org,33.0,Female,Togo,Basic,2021-11-10,2022-07-04,236.0,26-35,2021.0,11.0,Her media,Sci-Fi,172.23,2008,4.6,236.0
4,70694,4394,2022-02-21 05:58:48,179.36,Smart_TV,2022,2,Monday,TODD NELSON,phillipsmiranda@example.com,37.0,Female,Dominica,Standard,2022-03-30,2023-01-13,289.0,36-50,2022.0,3.0,Believe tend hand,Documentary,177.81,1986,3.0,289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,62620,21048,2021-04-30 06:39:22,72.79,Desktop,2021,4,Friday,Nicholas Walls,tracygoodwin@example.com,59.0,other,Saint Pierre and Miquelon,Basic,2021-04-11,2021-09-09,151.0,51-65,2021.0,4.0,Candidate career,Horror,72.52,1998,4.0,151.0
299996,58045,4930,2024-02-14 10:31:25,10.23,Desktop,2024,2,Wednesday,Mr. Jordan Taylor,devonrodgers@example.org,70.0,Female,Jordan,Standard,2024-12-26,2025-03-30,94.0,66-75,2024.0,12.0,Bank such,Sci-Fi,165.66,2002,3.4,94.0
299997,92884,11086,2022-07-20 18:49:34,112.94,Mobile,2022,7,Wednesday,Christina Castillo,marquezmatthew@example.org,38.0,Female,Kiribati,Standard,2023-11-10,2023-12-20,40.0,36-50,2023.0,11.0,Dog investment,Comedy,113.45,2014,3.2,40.0
299998,6089,38437,2025-12-23 06:51:40,173.18,Desktop,2025,12,Tuesday,Ernest Davis,richard83@example.com,30.0,other,Namibia,Basic,2022-09-16,2023-06-08,265.0,26-35,2022.0,9.0,Shoulder technology newspaper,Action,133.52,2005,4.6,265.0
299999,67059,26044,2026-02-03 01:17:51,126.36,Mobile,2026,2,Tuesday,Kathryn Diaz,sandrajohnson@example.net,72.0,Male,Heard Island and McDonald Islands,Standard,2022-03-29,2022-10-29,214.0,66-75,2022.0,3.0,Team long,Documentary,144.82,2000,3.3,214.0

In [ ]:
# feature Engineering : age group
bins = [0, 18, 30, 45, 60, 100]
labels = ['<18', '18-30', '31-45', '46-60', '60+']
full_df['age_group'] = pd.cut(full_df['age'], bins=bins, labels=labels)
full_df

,User_id,content_id,watch_date,watch_time_minutes,device_type,watch_year,watch_month,watch_dayofweek,name,email,age,gender,country,subscription_type,subscription_start,subscription_end,subscription_duration,age_group,start_year,start_month,title,genre,duration_min,release_year,rating,subscription_days
0,18717,44,2023-02-11 22:24:42,22.63,Smart_TV,2023,2,Saturday,MR. BRIAN LEBLANC,mark21@example.org,48.0,Male,Grenada,Standard,2024-11-12,2025-11-04,357.0,46-60,2024.0,11.0,Or show,Sci-Fi,139.96,2013,3.9,357.0
1,19693,17664,2021-12-22 00:19:53,102.44,Desktop,2021,12,Wednesday,Michael Garza,christinelopez@example.net,32.0,Female,Lebanon,Basic,2024-07-10,2025-06-20,345.0,31-45,2024.0,7.0,Responsibility can lawyer,Comedy,93.60,2006,2.6,345.0
2,7071,9197,2023-08-23 18:58:30,141.37,Desktop,2023,8,Wednesday,Daniel Franklin,morgandonovan@example.com,62.0,other,Djibouti,Basic,2023-03-21,2023-04-24,34.0,60+,2023.0,3.0,Step that,Comedy,30.92,2025,4.5,34.0
3,43487,18988,2025-02-22 04:38:32,140.06,Desktop,2025,2,Saturday,MONIQUE BLACK,kellimiller@example.org,33.0,Female,Togo,Basic,2021-11-10,2022-07-04,236.0,31-45,2021.0,11.0,Her media,Sci-Fi,172.23,2008,4.6,236.0
4,70694,4394,2022-02-21 05:58:48,179.36,Smart_TV,2022,2,Monday,TODD NELSON,phillipsmiranda@example.com,37.0,Female,Dominica,Standard,2022-03-30,2023-01-13,289.0,31-45,2022.0,3.0,Believe tend hand,Documentary,177.81,1986,3.0,289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,62620,21048,2021-04-30 06:39:22,72.79,Desktop,2021,4,Friday,Nicholas Walls,tracygoodwin@example.com,59.0,other,Saint Pierre and Miquelon,Basic,2021-04-11,2021-09-09,151.0,46-60,2021.0,4.0,Candidate career,Horror,72.52,1998,4.0,151.0
299996,58045,4930,2024-02-14 10:31:25,10.23,Desktop,2024,2,Wednesday,Mr. Jordan Taylor,devonrodgers@example.org,70.0,Female,Jordan,Standard,2024-12-26,2025-03-30,94.0,60+,2024.0,12.0,Bank such,Sci-Fi,165.66,2002,3.4,94.0
299997,92884,11086,2022-07-20 18:49:34,112.94,Mobile,2022,7,Wednesday,Christina Castillo,marquezmatthew@example.org,38.0,Female,Kiribati,Standard,2023-11-10,2023-12-20,40.0,31-45,2023.0,11.0,Dog investment,Comedy,113.45,2014,3.2,40.0
299998,6089,38437,2025-12-23 06:51:40,173.18,Desktop,2025,12,Tuesday,Ernest Davis,richard83@example.com,30.0,other,Namibia,Basic,2022-09-16,2023-06-08,265.0,18-30,2022.0,9.0,Shoulder technology newspaper,Action,133.52,2005,4.6,265.0
299999,67059,26044,2026-02-03 01:17:51,126.36,Mobile,2026,2,Tuesday,Kathryn Diaz,sandrajohnson@example.net,72.0,Male,Heard Island and McDonald Islands,Standard,2022-03-29,2022-10-29,214.0,60+,2022.0,3.0,Team long,Documentary,144.82,2000,3.3,214.0

In [ ]:
# Watch day of week, month, year
full_df['watch_year'] = full_df['watch_date'].dt.year
full_df['watch_month'] = full_df['watch_date'].dt.month
full_df['watch_dayofweek'] = full_df['watch_date'].dt.day_name()
full_df

,User_id,content_id,watch_date,watch_time_minutes,device_type,watch_year,watch_month,watch_dayofweek,name,email,age,gender,country,subscription_type,subscription_start,subscription_end,subscription_duration,age_group,start_year,start_month,title,genre,duration_min,release_year,rating,subscription_days
0,18717,44,2023-02-11 22:24:42,22.63,Smart_TV,2023,2,Saturday,MR. BRIAN LEBLANC,mark21@example.org,48.0,Male,Grenada,Standard,2024-11-12,2025-11-04,357.0,46-60,2024.0,11.0,Or show,Sci-Fi,139.96,2013,3.9,357.0
1,19693,17664,2021-12-22 00:19:53,102.44,Desktop,2021,12,Wednesday,Michael Garza,christinelopez@example.net,32.0,Female,Lebanon,Basic,2024-07-10,2025-06-20,345.0,31-45,2024.0,7.0,Responsibility can lawyer,Comedy,93.60,2006,2.6,345.0
2,7071,9197,2023-08-23 18:58:30,141.37,Desktop,2023,8,Wednesday,Daniel Franklin,morgandonovan@example.com,62.0,other,Djibouti,Basic,2023-03-21,2023-04-24,34.0,60+,2023.0,3.0,Step that,Comedy,30.92,2025,4.5,34.0
3,43487,18988,2025-02-22 04:38:32,140.06,Desktop,2025,2,Saturday,MONIQUE BLACK,kellimiller@example.org,33.0,Female,Togo,Basic,2021-11-10,2022-07-04,236.0,31-45,2021.0,11.0,Her media,Sci-Fi,172.23,2008,4.6,236.0
4,70694,4394,2022-02-21 05:58:48,179.36,Smart_TV,2022,2,Monday,TODD NELSON,phillipsmiranda@example.com,37.0,Female,Dominica,Standard,2022-03-30,2023-01-13,289.0,31-45,2022.0,3.0,Believe tend hand,Documentary,177.81,1986,3.0,289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,62620,21048,2021-04-30 06:39:22,72.79,Desktop,2021,4,Friday,Nicholas Walls,tracygoodwin@example.com,59.0,other,Saint Pierre and Miquelon,Basic,2021-04-11,2021-09-09,151.0,46-60,2021.0,4.0,Candidate career,Horror,72.52,1998,4.0,151.0
299996,58045,4930,2024-02-14 10:31:25,10.23,Desktop,2024,2,Wednesday,Mr. Jordan Taylor,devonrodgers@example.org,70.0,Female,Jordan,Standard,2024-12-26,2025-03-30,94.0,60+,2024.0,12.0,Bank such,Sci-Fi,165.66,2002,3.4,94.0
299997,92884,11086,2022-07-20 18:49:34,112.94,Mobile,2022,7,Wednesday,Christina Castillo,marquezmatthew@example.org,38.0,Female,Kiribati,Standard,2023-11-10,2023-12-20,40.0,31-45,2023.0,11.0,Dog investment,Comedy,113.45,2014,3.2,40.0
299998,6089,38437,2025-12-23 06:51:40,173.18,Desktop,2025,12,Tuesday,Ernest Davis,richard83@example.com,30.0,other,Namibia,Basic,2022-09-16,2023-06-08,265.0,18-30,2022.0,9.0,Shoulder technology newspaper,Action,133.52,2005,4.6,265.0
299999,67059,26044,2026-02-03 01:17:51,126.36,Mobile,2026,2,Tuesday,Kathryn Diaz,sandrajohnson@example.net,72.0,Male,Heard Island and McDonald Islands,Standard,2022-03-29,2022-10-29,214.0,60+,2022.0,3.0,Team long,Documentary,144.82,2000,3.3,214.0

In [ ]:
# check consistency
full_df.describe()

,User_id,content_id,watch_date,watch_time_minutes,watch_year,watch_month,age,subscription_start,subscription_end,subscription_duration,start_year,start_month,duration_min,release_year,rating,subscription_days
count,300000.000000,300000.000000,300000,300000.000000,300000.000000,300000.00000,299512.000000,299512,299512,299512.000000,299512.000000,299512.000000,300000.000000,300000.000000,300000.000000,299512.000000
mean,50173.773027,24983.898667,2023-10-07 10:15:46.091603456,92.639248,2023.264343,6.52676,46.552732,2023-10-07 09:45:20.553433600,2024-04-21 22:34:26.112877056,197.534092,2023.266677,6.514834,99.663791,2002.440050,3.393900,197.534092
min,172.000000,1.000000,2021-04-07 13:19:23,5.000000,2021.000000,1.00000,18.000000,2021-04-06 00:00:00,2021-05-11 00:00:00,30.000000,2021.000000,1.000000,20.000000,1980.000000,2.000000,30.000000
25%,25175.000000,12444.000000,2022-07-08 11:17:56.750000128,48.760000,2022.000000,4.00000,32.000000,2022-07-09 00:00:00,2023-01-21 00:00:00,114.000000,2022.000000,4.000000,59.520000,1991.000000,2.700000,114.000000
50%,50287.000000,24991.000000,2023-10-07 21:44:32.500000,92.690000,2023.000000,7.00000,47.000000,2023-10-08 00:00:00,2024-04-21 12:00:00,197.000000,2023.000000,7.000000,99.510000,2002.000000,3.400000,197.000000
75%,75227.250000,37529.000000,2025-01-05 09:47:37.249999872,136.520000,2025.000000,10.00000,61.000000,2025-01-05 00:00:00,2025-07-23 00:00:00,281.000000,2025.000000,10.000000,139.620000,2014.000000,4.100000,281.000000
max,100171.000000,50000.000000,2026-04-07 17:58:09,180.000000,2026.000000,12.00000,75.000000,2026-04-06 00:00:00,2027-04-06 00:00:00,365.000000,2026.000000,12.000000,180.000000,2025.000000,4.800000,365.000000
std,28871.957949,14458.128754,NaN,50.552895,1.479941,3.44957,16.755296,NaN,NaN,96.819906,1.480043,3.451450,46.211786,13.242861,0.810801,96.819906