In [12]:
!pip install faker pandas

Requirement already satisfied: faker in /usr/local/lib/python3.12/dist-packages (40.12.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [13]:
from faker import Faker
import pandas as pd
import random
import datetime
fake = Faker()

In [14]:


# Step 2: Initialize Faker
fake = Faker()

# Step 3: Generate Users Data
users = []

for i in range(100000):  # 50k users
    # Subscription dates
    start_date = fake.date_between(start_date='-5y', end_date='today')
    end_date = start_date + datetime.timedelta(days=random.randint(30, 365))

    # Email: sometimes missing
    email = fake.unique.email()  # guarantees no duplicates
    # Name: messy capitalization
    name = fake.name()
    if random.random() > 0.5:
        name = name.upper()

    # Age: 18–75
    age = random.randint(18, 75)

    # Gender
    gender = random.choice(['Male', 'Female', 'other'])

    # Country
    country = fake.country()

    # Subscription type
    subscription_type = random.choice(['Basic', 'Standard', 'Premium'])

    # Format dates for MySQL
    start_date = start_date.strftime('%Y-%m-%d')
    end_date = end_date.strftime('%Y-%m-%d')

    users.append([
        name,
        email,
        age,
        gender,
        country,
        subscription_type,
        start_date,
        end_date
    ])

# Step 4: Create DataFrame
users_df = pd.DataFrame(users, columns=[
    'name',
    'email',
    'age',
    'gender',
    'country',
    'subscription_type',
    'subscription_start',
    'subscription_end'
])

# Step 5: Save CSV for MySQL
# NULL emails will be saved as NULL (MySQL-compatible)
users_df.to_csv("users.csv", index=False, na_rep='NULL')

# Step 6: Check first 5 rows
users_df.head(10)

,name,email,age,gender,country,subscription_type,subscription_start,subscription_end
0,SCOTT MEYER,amysherman@example.org,44,other,Estonia,Basic,2025-03-13,2025-04-12
1,Gabriel Gill,billy05@example.org,75,other,Madagascar,Standard,2023-09-02,2023-11-18
2,ANGELA BREWER,nhines@example.net,49,Female,Afghanistan,Standard,2025-05-25,2025-12-01
3,Eric Bates,kimberlywhite@example.net,26,other,Honduras,Premium,2025-09-04,2026-04-19
4,SARA RODRIGUEZ,thompsonhannah@example.org,73,Male,Burundi,Premium,2026-02-24,2026-10-26
5,Derrick Moses,john03@example.net,59,Female,Mongolia,Premium,2021-10-28,2022-04-17
6,Marco Lopez,phall@example.com,35,other,Cayman Islands,Basic,2022-04-19,2023-04-08
7,Ana Johnson,markkidd@example.org,43,other,Saint Pierre and Miquelon,Basic,2023-06-07,2024-04-30
8,Christopher Martinez,lvasquez@example.com,55,Male,Netherlands,Premium,2022-05-20,2023-01-05
9,Carol Wheeler,tracey08@example.org,53,Male,Guam,Premium,2023-07-06,2023-11-28

In [15]:
# Step: Generate View table data
fake = Faker()

genres = ['Action', 'Horror', 'Comedy', 'Drama', 'Sci-Fi', 'Documentary', 'Romance', 'Thriller']

content = []

for i in range(50000):
    title = fake.sentence(nb_words=3).replace('.', '')

    # realistic duration
    duration = round(random.uniform(20, 180), 2)

    # realistic rating (more centered around 3–4)
    rating = round(random.uniform(2.0, 4.8), 1)

    content.append([
        title,
        random.choice(genres),
        duration,
        random.randint(1980, 2025),
        rating
    ])

content_df = pd.DataFrame(content, columns=[
    'title',
    'genre',
    'duration_min',
    'release_year',
    'rating'
])

content_df.head()

                       title        genre  duration_min  release_year  rating
0           Street trip dark       Action        166.23          2018     3.4
1         Than rather season       Action        178.84          1992     3.6
2               Husband join  Documentary        106.64          2023     4.7
3                       Word       Horror        162.47          1994     3.5
4  Before believe successful       Comedy        101.02          2024     2.4

In [16]:
# Step: Generate View table data

from faker import Faker
import pandas as pd
import random
import datetime

fake = Faker()

# ---- 1. Define valid IDs ----
# User IDs that actually exist in MySQL users table
valid_user_ids = list(range(172, 100172))  # MIN=172, MAX=100171

# Content IDs that actually exist in MySQL content table
valid_content_ids = list(range(1, 50001))  # assuming 50,000 content rows

# Device types
device_types = ['Mobile', 'Desktop', 'Smart_TV', 'Tablet']

# ---- 2. Generate messy View data ----
view_data = []
num_rows = 300000  # number of view records

for _ in range(num_rows):
    user_id = random.choice(valid_user_ids)           # only valid User_id
    content_id = random.choice(valid_content_ids)    # only valid Content_id
    watch_date = fake.date_time_between(start_date='-5y', end_date='now')
    watch_date_str = watch_date.strftime('%Y-%m-%d %H:%M:%S')  # MySQL datetime format
    watch_time = round(random.uniform(5, 180), 2)   # minutes watched
    device = random.choice(device_types)

    # Append as a row
    view_data.append([user_id, content_id, watch_date_str, watch_time, device])

# ---- 3. Create DataFrame ----
view_df = pd.DataFrame(view_data, columns=[
    'User_id', 'content_id', 'watch_date', 'watch_time_minutes', 'device_type'
])

# ---- 4. Preview ----
print(view_df.head())

# ---- 5. Export to CSV for MySQL LOAD DATA ----
view_df.to_csv("view.csv", index=False, na_rep='NULL')
print("CSV file saved as 'view.csv' ready for MySQL import!")

   User_id  content_id           watch_date  watch_time_minutes device_type
0    73110       15198  2026-01-09 16:33:24              127.89     Desktop
1    68087       42436  2024-05-30 06:25:16              130.03     Desktop
2    40370       18668  2021-06-27 19:52:42               71.82      Mobile
3    87719       30122  2024-12-10 02:41:49              173.32    Smart_TV
4    88759       46093  2022-10-27 00:45:08                7.54    Smart_TV
CSV file saved as 'view.csv' ready for MySQL import!

In [17]:
from google.colab import files

In [18]:
users_df.to_csv('users.csv', index=False)
content_df.to_csv('content.csv', index=False)
view_df.to_csv('view.csv', index=False)
files.download('users.csv')
files.download('content.csv')
files.download('view.csv')

In [19]:
# import libraries
import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns

In [20]:
# display all columns in pandas
pd.set_option('display.max_columns',None)

In [43]:
print('users tables:')
print(users_df.info())
print(users_df.describe)
print(users_df.head())
print(users_df.isnull())

users tables:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   name                   100000 non-null  object
 1   email                  100000 non-null  object
 2   age                    100000 non-null  int64
 3   gender                 100000 non-null  category
 4   country                100000 non-null  object
 5   subscription_type      100000 non-null  category
 6   subscription_start     100000 non-null  datetime64[ns]
 7   subscription_end       100000 non-null  datetime64[ns]
 8   subscription_duration  100000 non-null  int64
 9   age_group              98333 non-null   category
 10  start_year             100000 non-null  int32
 11  start_month            100000 non-null  int32
dtypes: category(3), datetime64[ns](2), int32(2), int64(2), object(3)
memory usage: 6.4+ MB
None
<bound method NDFrame.describe of                      name                       email  age  gender  \
0             SCOTT MEYER      amysherman@example.org   44   other
1            Gabriel Gill         billy05@example.org   75   other
2           ANGELA BREWER          nhines@example.net   49  Female
3              Eric Bates   kimberlywhite@example.net   26   other
4          SARA RODRIGUEZ  thompsonhannah@example.org   73    Male
...                   ...                         ...  ...     ...
99995   Cody Stephens DDS  danielsrichard@example.net   70  Female
99996      CHRISTY PARKER       kristin63@example.com   28    Male
99997         BRIAN BROWN   newmancharles@example.org   72    Male
99998         Rose Newton    michaeladams@example.org   45    Male
99999  Jennifer Patterson         nbailey@example.net   62    Male

                                    country subscription_type  \
0                                   Estonia             Basic
1                                Madagascar          Standard
2                               Afghanistan          Standard
3                                  Honduras           Premium
4                                   Burundi           Premium
...                                     ...               ...
99995                              Guernsey           Premium
99996  United States Minor Outlying Islands             Basic
99997                               Reunion             Basic
99998                               Bolivia             Basic
99999                               Jamaica             Basic

      subscription_start subscription_end  subscription_duration age_group  \
0             2025-03-13       2025-04-12                     30     36-50
1             2023-09-02       2023-11-18                     77     66-75
2             2025-05-25       2025-12-01                    190     36-50
3             2025-09-04       2026-04-19                    227     26-35
4             2026-02-24       2026-10-26                    244     66-75
...                  ...              ...                    ...       ...
99995         2021-12-09       2022-03-02                     83     66-75
99996         2024-09-20       2024-10-27                     37     26-35
99997         2022-08-11       2022-10-13                     63     66-75
99998         2024-03-10       2025-01-29                    325     36-50
99999         2025-05-03       2026-04-19                    351     51-65

       start_year  start_month
0            2025            3
1            2023            9
2            2025            5
3            2025            9
4            2026            2
...           ...          ...
99995        2021           12
99996        2024            9
99997        2022            8
99998        2024            3
99999        2025            5

[100000 rows x 12 columns]>
             name                       email  age  gender      country  \
0     SCOTT MEYER      amysherman@example.org   44   other      Estonia
1    Gabriel Gill         billy05@example.org   75   other   Madagascar
2   ANGELA BREWER          nhines@example.net   49  Female  Afghanistan
3      Eric Bates   kimberlywhite@example.net   26   other     Honduras
4  SARA RODRIGUEZ  thompsonhannah@example.org   73    Male      Burundi

  subscription_type subscription_start subscription_end  \
0             Basic         2025-03-13       2025-04-12
1          Standard         2023-09-02       2023-11-18
2          Standard         2025-05-25       2025-12-01
3           Premium         2025-09-04       2026-04-19
4           Premium         2026-02-24       2026-10-26

   subscription_duration age_group  start_year  start_month
0                     30     36-50        2025            3
1                     77     66-75        2023            9
2                    190     36-50        2025            5
3                    227     26-35        2025            9
4                    244     66-75        2026            2
        name  email    age  gender  country  subscription_type  \
0      False  False  False   False    False              False
1      False  False  False   False    False              False
2      False  False  False   False    False              False
3      False  False  False   False    False              False
4      False  False  False   False    False              False
...      ...    ...    ...     ...      ...                ...
99995  False  False  False   False    False              False
99996  False  False  False   False    False              False
99997  False  False  False   False    False              False
99998  False  False  False   False    False              False
99999  False  False  False   False    False              False

       subscription_start  subscription_end  subscription_duration  age_group  \
0                   False             False                  False      False
1                   False             False                  False      False
2                   False             False                  False      False
3                   False             False                  False      False
4                   False             False                  False      False
...                   ...               ...                    ...        ...
99995               False             False                  False      False
99996               False             False                  False      False
99997               False             False                  False      False
99998               False             False                  False      False
99999               False             False                  False      False

       start_year  start_month
0           False        False
1           False        False
2           False        False
3           False        False
4           False        False
...           ...          ...
99995       False        False
99996       False        False
99997       False        False
99998       False        False
99999       False        False

[100000 rows x 12 columns]

In [41]:
# checking missinf users value
print(users_df.isnull().sum())

name                        0
email                       0
age                         0
gender                      0
country                     0
subscription_type           0
subscription_start          0
subscription_end            0
subscription_duration       0
age_group                1667
start_year                  0
start_month                 0
dtype: int64

In [40]:
# checking types
print(users_df.dtypes)

name                             object
email                            object
age                               int64
gender                         category
country                          object
subscription_type              category
subscription_start       datetime64[ns]
subscription_end         datetime64[ns]
subscription_duration             int64
age_group                      category
start_year                        int32
start_month                       int32
dtype: object

In [39]:
# subscription_start and subscription_end still in object so changing in into datetime
users_df['subscription_start'] = pd.to_datetime(users_df['subscription_start'])
users_df['subscription_end'] = pd.to_datetime(users_df['subscription_end'])
# now we wil see datetime
print(users_df.dtypes)

name                             object
email                            object
age                               int64
gender                         category
country                          object
subscription_type              category
subscription_start       datetime64[ns]
subscription_end         datetime64[ns]
subscription_duration             int64
age_group                      category
start_year                        int32
start_month                       int32
dtype: object

In [25]:
# now making gender and subscription_type into categorical

users_df['gender'] = users_df['gender'].astype('category')
users_df['subscription_type'] = users_df['subscription_type'].astype('category')
# now checking dtypes
print(users_df.dtypes)

name                          object
email                         object
age                            int64
gender                      category
country                       object
subscription_type           category
subscription_start    datetime64[ns]
subscription_end      datetime64[ns]
dtype: object

In [38]:
# creating a new feature called subscription_duration
users_df['subscription_duration'] = (
    users_df['subscription_end'] - users_df['subscription_start']
    ).dt.days
print(users_df['subscription_duration'])

0         30
1         77
2        190
3        227
4        244
        ...
99995     83
99996     37
99997     63
99998    325
99999    351
Name: subscription_duration, Length: 100000, dtype: int64

In [27]:
# creating another new gfeature age_group
users_df['age_group'] = pd.cut (
    users_df['age'],
    bins = [18,25,35,50,65,75],
    labels=['18-25','26-35','36-50','51-65','66-75']
)
print(users_df['age_group'])

0        36-50
1        66-75
2        36-50
3        26-35
4        66-75
         ...
99995    66-75
99996    26-35
99997    66-75
99998    36-50
99999    51-65
Name: age_group, Length: 100000, dtype: category
Categories (5, object): ['18-25' < '26-35' < '36-50' < '51-65' < '66-75']

In [28]:
# extracting year and month
users_df['start_year'] = users_df['subscription_start'].dt.year
users_df['start_month'] = users_df['subscription_start'].dt.month
print(users_df['start_year'])
print(users_df['start_month'])

0        2025
1        2023
2        2025
3        2025
4        2026
         ...
99995    2021
99996    2024
99997    2022
99998    2024
99999    2025
Name: start_year, Length: 100000, dtype: int32
0         3
1         9
2         5
3         9
4         2
         ..
99995    12
99996     9
99997     8
99998     3
99999     5
Name: start_month, Length: 100000, dtype: int32

In [29]:
users_df.head(5)

,name,email,age,gender,country,subscription_type,subscription_start,subscription_end,subscription_duration,age_group,start_year,start_month
0,SCOTT MEYER,amysherman@example.org,44,other,Estonia,Basic,2025-03-13,2025-04-12,30,36-50,2025,3
1,Gabriel Gill,billy05@example.org,75,other,Madagascar,Standard,2023-09-02,2023-11-18,77,66-75,2023,9
2,ANGELA BREWER,nhines@example.net,49,Female,Afghanistan,Standard,2025-05-25,2025-12-01,190,36-50,2025,5
3,Eric Bates,kimberlywhite@example.net,26,other,Honduras,Premium,2025-09-04,2026-04-19,227,26-35,2025,9
4,SARA RODRIGUEZ,thompsonhannah@example.org,73,Male,Burundi,Premium,2026-02-24,2026-10-26,244,66-75,2026,2

In [30]:
# users per subscription type
users_df.groupby('subscription_type').size()

/tmp/ipykernel_7139/642442302.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  users_df.groupby('subscription_type').size()

subscription_type
Basic       33250
Premium     33300
Standard    33450
dtype: int64

In [31]:
# most pouplar
users_df.groupby('subscription_type').size().sort_values(ascending = False)

/tmp/ipykernel_7139/1736296505.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  users_df.groupby('subscription_type').size().sort_values(ascending = False)

subscription_type
Standard    33450
Premium     33300
Basic       33250
dtype: int64

In [46]:
# average subscription day
users_df.groupby('subscription_type')['subscription_duration'].mean().sort_values(ascending = False)

/tmp/ipykernel_7139/3999752269.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  users_df.groupby('subscription_type')['subscription_duration'].mean().sort_values(ascending = False)

subscription_type
Standard    197.261256
Premium     197.203093
Basic       196.619729
Name: subscription_duration, dtype: float64

In [50]:
# combine count and Average

users_df.groupby('subscription_type').agg(
     user_count =('name' , 'count'),
    avg_subscription_duration =( 'subscription_duration' , 'mean')
)

/tmp/ipykernel_7139/2442647106.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  users_df.groupby('subscription_type').agg(

                   user_count  avg_subscription_duration
subscription_type
Basic                   33250                 196.619729
Premium                 33300                 197.203093
Standard                33450                 197.261256